<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDc8-Dx-6PHHH92" ignored="0" name="Default test" tests="1" failures="1" timestamp="26 Oct 2018 10:27:40 GMT" time="107.983" errors="0">
  <testcase name="startingTest" time="30.597" classname="ireff.OperatorsList_AppTest1">
    <failure type="java.lang.Exception" message="Element not found: new UiSelector().resourceId(&amp;quot;in.ireff.android:id/imageView1&amp;quot;)">
      <![CDATA[java.lang.Exception: Element not found: new UiSelector().resourceId("in.ireff.android:id/imageView1")
at AppiumCore.ElementAction.waitForElement(ElementAction.java:262)
at AppiumCore.ElementAction.getElement(ElementAction.java:60)
at AppiumCore.ElementAction.tap(ElementAction.java:105)
at IreffImplements.ireff_Implements.validNewOperatorsList(ireff_Implements.java:39)
at ireff.OperatorsList_AppTest1.startingTest(OperatorsList_AppTest1.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- startingTest -->
</testsuite> <!-- Default test -->
